"""
GeoGuard AI

API Schemas

Author: Shivam Salve
"""

from pydantic import BaseModel, Field


# ==========================================================
# Assessment
# ==========================================================

class AssessmentSchema(BaseModel):
    """
    Disaster assessment returned by GeoGuard AI.
    """

    severity: str = Field(
        ...,
        description="Overall disaster severity"
    )

    impact: str = Field(
        ...,
        description="Estimated disaster impact"
    )

    confidence: float = Field(
        ...,
        description="Overall AI confidence (%)",
        ge=0.0,
        le=100.0,
    )

    landcover: dict[str, float] = Field(
        default_factory=dict,
        description="Land cover distribution (%)"
    )

    flood: dict[str, float] = Field(
        default_factory=dict,
        description="Flood statistics (%)"
    )

    damage: dict[str, float] = Field(
        default_factory=dict,
        description="Building damage statistics (%)"
    )


# ==========================================================
# Reasoning
# ==========================================================

class ReasoningSchema(BaseModel):
    """
    AI reasoning generated by Gemma.
    """

    summary: str = Field(
        ...,
        description="Executive summary"
    )

    analysis: str = Field(
        ...,
        description="Detailed AI analysis"
    )

    priority: str = Field(
        ...,
        description="Emergency priority"
    )

    recommendations: list[str] = Field(
        default_factory=list,
        description="Recommended emergency actions"
    )


# ==========================================================
# Generated Files
# ==========================================================

class FilesSchema(BaseModel):
    """
    Generated output files.
    """

    prediction: str | None = Field(
        default=None,
        description="Prediction mask image"
    )

    overlay: str | None = Field(
        default=None,
        description="Overlay image"
    )

    html_report: str | None = Field(
        default=None,
        description="Generated HTML report"
    )

    pdf_report: str | None = Field(
        default=None,
        description="Generated PDF report"
    )


# ==========================================================
# Prediction Response
# ==========================================================

class PredictionResponse(BaseModel):
    """
    Response returned by POST /api/predict.
    """

    success: bool = Field(
        default=True,
        description="Prediction status"
    )

    message: str = Field(
        default="Prediction completed successfully.",
        description="Status message"
    )

    assessment: AssessmentSchema

    reasoning: ReasoningSchema

    files: FilesSchema

# ==========================================================
# Report Response
# ==========================================================

class ReportFilesSchema(BaseModel):
    """
    Generated report files.
    """

    html_report: str | None = Field(
        default=None,
        description="Generated HTML report"
    )

    pdf_report: str | None = Field(
        default=None,
        description="Generated PDF report"
    )


class ReportResponse(BaseModel):
    """
    Response returned by POST /api/report.
    """

    success: bool = True

    message: str = "Report generated successfully."

    report: ReportFilesSchema
    

# ==========================================================
# Health Response
# ==========================================================

class HealthResponse(BaseModel):
    """
    Response returned by GET /api/health.
    """

    status: str

    service: str

    version: str | None = None


# ==========================================================
# Error Response
# ==========================================================

class ErrorResponse(BaseModel):
    """
    Standard API error response.
    """

    success: bool = False

    error: str

    detail: str